import { User, Patient, HealthRecord, DiagnosticResult, MedicationOrder, TreatmentLog, AdmissionEntry, AuditLog } from "./types";

export const DEMO_USERS: Record<string, { password: string; user: User }> = {
  "patient01": {
    password: "pass",
    user: {
      id: "P-2024-001",
      name: "Maria Santos",
      role: "patient",
      title: "Patient",
      department: "Outpatient / Inpatient",
      avatarInitials: "MS",
      patientId: "P-2024-001",
    },
  },
  "dr.reyes": {
    password: "pass",
    user: {
      id: "D-001",
      name: "Dr. Jose Reyes, MD",
      role: "doctor",
      title: "Attending Physician & Cardiologist",
      department: "Internal Medicine & OPD",
      avatarInitials: "JR",
    },
  },
  "nurse.angel": {
    password: "pass",
    user: {
      id: "N-001",
      name: "Angel Mae, RN",
      role: "nurse",
      title: "Senior Charge Nurse",
      department: "Emergency & Medical Ward",
      avatarInitials: "AM",
    },
  },
  "staff.admissions": {
    password: "pass",
    user: {
      id: "S-101",
      name: "Jendy Perez",
      role: "staff",
      title: "Admissions & Records Officer",
      department: "Patient Admissions & Front Desk",
      avatarInitials: "JP",
    },
  },
  "admin.privacy": {
    password: "pass",
    user: {
      id: "A-001",
      name: "Atty. Roberto Ramos",
      role: "admin",
      title: "Data Privacy Officer & Hospital Admin",
      department: "Data Privacy, Security & Compliance",
      avatarInitials: "RR",
    },
  },
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "P-2024-001",
    name: "Maria Santos",
    dob: "1992-04-14",
    age: 34,
    gender: "Female",
    civilStatus: "Married",
    contact: "0917-555-1234",
    address: "Block 14 Lot 3, Acacia St., San Antonio, Pasig City",
    emergencyContact: {
      name: "Juan Santos",
      relationship: "Spouse",
      phone: "0918-444-9876",
    },
    bloodType: "O+",
    allergies: ["Penicillin", "NSAIDs"],
    chiefComplaint: "Periodic elevated blood pressure readings and mild occipital headaches.",
    admissionStatus: "Outpatient",
    ward: "OPD Clinic 3",
    bed: "Chair 04",
    attendingPhysician: "Dr. Jose Reyes, MD",
    registeredAt: "2024-01-12",
  },
  {
    id: "P-2024-002",
    name: "Carlos Dela Cruz",
    dob: "1978-08-20",
    age: 48,
    gender: "Male",
    civilStatus: "Married",
    contact: "0920-888-4321",
    address: "24 Mahogany Lane, Greenhills, San Juan City",
    emergencyContact: {
      name: "Elena Dela Cruz",
      relationship: "Spouse",
      phone: "0921-777-6543",
    },
    bloodType: "A+",
    allergies: ["Sulfa drugs"],
    chiefComplaint: "Acute abdominal pain, right lower quadrant tenderness with fever.",
    admissionStatus: "Admitted",
    ward: "Surgical Ward",
    bed: "Bed 204-A",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admissionDate: "2026-09-11 14:30",
    registeredAt: "2024-03-05",
  },
  {
    id: "P-2024-003",
    name: "Luzviminda Garcia",
    dob: "1960-11-03",
    age: 65,
    gender: "Female",
    civilStatus: "Widowed",
    contact: "0919-333-7711",
    address: "78 Rosal St., Barangay Kapitolyo, Pasig City",
    emergencyContact: {
      name: "Mark Garcia",
      relationship: "Son",
      phone: "0919-222-8844",
    },
    bloodType: "B+",
    allergies: ["Latex", "Aspirin"],
    chiefComplaint: "Shortness of breath on exertion and bilateral lower extremity edema.",
    admissionStatus: "Admitted",
    ward: "Medical Ward",
    bed: "Bed 312-B",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admissionDate: "2026-09-09 09:15",
    registeredAt: "2023-08-19",
  },
  {
    id: "P-2024-004",
    name: "Eduardo Mendoza",
    dob: "2001-02-18",
    age: 25,
    gender: "Male",
    civilStatus: "Single",
    contact: "0932-111-9900",
    address: "15 Dahlia St., Mandaluyong City",
    emergencyContact: {
      name: "Carmela Mendoza",
      relationship: "Mother",
      phone: "0932-555-6677",
    },
    bloodType: "O-",
    allergies: ["None known"],
    chiefComplaint: "Blunt chest trauma following motorcycle fall. Hemodynamically stable.",
    admissionStatus: "Observation",
    ward: "Emergency Observation",
    bed: "Bed ER-03",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admissionDate: "2026-09-12 06:45",
    registeredAt: "2026-09-12",
  },
];

export const INITIAL_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: "EHR-2026-0910",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    date: "September 10, 2026",
    type: "OPD Visit",
    doctor: "Dr. Jose Reyes, MD",
    diagnosis: "Essential Hypertension — Stage 1",
    icd10Code: "I10",
    subjective: "Patient reports occasional morning headaches and neck stiffness over past 2 weeks. Complies with low-salt diet mostly, denies chest pain or visual changes.",
    objective: "Alert, oriented x3, ambulatory without distress. Heart sounds regular S1/S2, no murmurs. Lungs clear to auscultation.",
    assessment: "Controlled Stage 1 Essential Hypertension with mild transient elevation; asymptomatic dyslipidemia.",
    plan: "Continue Amlodipine 5mg once daily; initiate Atorvastatin 20mg bedtime. Low sodium (<2g/day) lifestyle counseling. Re-evaluate in 2 weeks with home BP log.",
    notes: "Patient advised to maintain daily blood pressure log in morning and evening.",
    internalClinicianNotes: "CONFIDENTIAL CLINICAL IMPRESSION: Patient exhibits mild compliance hesitation with Atorvastatin due to hearsay regarding statins. Counsel with care. Screen for familial hypercholesterolemia on next visit.",
    vitals: {
      bp: "145/92 mmHg",
      hr: "82 bpm",
      temp: "36.8°C",
      wt: "68 kg",
      spo2: "99%",
      rr: "16 cpm",
    },
  },
  {
    id: "EHR-2026-0822",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    date: "August 22, 2026",
    type: "Specialist Follow-up",
    doctor: "Dr. Jose Reyes, MD",
    diagnosis: "Dyslipidemia — Mild Hypercholesterolemia",
    icd10Code: "E78.0",
    subjective: "Follow-up for routine annual corporate health check results. No specific complaints.",
    objective: "Lipid profile review: Total Cholesterol 215 mg/dL, LDL 148 mg/dL. Normal abdominal exam.",
    assessment: "Mild Dyslipidemia, low atherosclerotic cardiovascular risk category.",
    plan: "Dietary modification, 30 minutes daily aerobic exercise. Re-check complete lipid panel in 3 months.",
    notes: "Given dietary brochure on Mediterranean heart-healthy meals.",
    internalClinicianNotes: "CONFIDENTIAL CLINICAL IMPRESSION: Evaluate secondary causes of elevated LDL if lifestyle therapy yields < 10% reduction. Rule out subclinical hypothyroidism.",
    vitals: {
      bp: "138/88 mmHg",
      hr: "78 bpm",
      temp: "36.6°C",
      wt: "67.5 kg",
      spo2: "98%",
      rr: "18 cpm",
    },
  },
  {
    id: "EHR-2026-0911",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    date: "September 11, 2026",
    type: "Inpatient Progress",
    doctor: "Dr. Jose Reyes, MD",
    diagnosis: "Acute Appendicitis — Early Catarrhal",
    icd10Code: "K35.80",
    subjective: "Patient admitted through ER with periumbilical pain migrating to right iliac fossa, anorexia and low-grade pyrexia.",
    objective: "McBurney's point tenderness positive, Rovsing's sign positive. Guarding noted. WBC 14.5 x 10^3/uL.",
    assessment: "Acute uncomplicated appendicitis.",
    plan: "NPO order, IV Ceftriaxone 1g q24h + Metronidazole 500mg q8h. Pre-operative workup completed, surgical consult called.",
    notes: "Consent for exploratory laparotomy / laparoscopic appendectomy obtained.",
    vitals: {
      bp: "130/85 mmHg",
      hr: "96 bpm",
      temp: "38.2°C",
      wt: "74 kg",
      spo2: "98%",
      rr: "20 cpm",
    },
  },
];

export const INITIAL_LAB_RESULTS: DiagnosticResult[] = [
  {
    id: "LAB-2026-8801",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    test: "Complete Blood Count (CBC) with Platelets",
    category: "Hematology",
    date: "Sep 10, 2026",
    status: "Ready",
    specimenType: "Whole Blood (EDTA)",
    orderingPhysician: "Dr. Jose Reyes, MD",
    releasedBy: "Jumie Palma, RMT (License #044812)",
    summary: "All hematological indices are within acceptable physiological limits. No leukocytosis or thrombocytopenia.",
    items: [
      { name: "Hemoglobin", value: "13.8 g/dL", ref: "12.0–16.0", flag: null, unit: "g/dL" },
      { name: "White Blood Cells (WBC)", value: "7.2 × 10³/μL", ref: "4.5–11.0", flag: null, unit: "× 10³/μL" },
      { name: "Platelet Count", value: "210 × 10³/μL", ref: "150–400", flag: null, unit: "× 10³/μL" },
      { name: "Hematocrit (PCV)", value: "42.0%", ref: "37.0–48.0", flag: null, unit: "%" },
      { name: "Neutrophils", value: "62%", ref: "50–70", flag: null, unit: "%" },
      { name: "Lymphocytes", value: "31%", ref: "20–40", flag: null, unit: "%" },
    ],
  },
  {
    id: "LAB-2026-8802",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    test: "Fasting Lipid Profile",
    category: "Clinical Chemistry",
    date: "Sep 10, 2026",
    status: "Ready",
    specimenType: "Serum (12-hour fast)",
    orderingPhysician: "Dr. Jose Reyes, MD",
    releasedBy: "Jumie Palma, RMT (License #044812)",
    summary: "Mild elevation noted in Total Cholesterol and LDL fraction. Follow-up statin therapy indicated.",
    items: [
      { name: "Total Cholesterol", value: "215 mg/dL", ref: "< 200", flag: "H", unit: "mg/dL" },
      { name: "LDL Direct Cholesterol", value: "148 mg/dL", ref: "< 100", flag: "H", unit: "mg/dL" },
      { name: "HDL Good Cholesterol", value: "52 mg/dL", ref: "> 50", flag: null, unit: "mg/dL" },
      { name: "Triglycerides", value: "138 mg/dL", ref: "< 150", flag: null, unit: "mg/dL" },
      { name: "VLDL Cholesterol", value: "27.6 mg/dL", ref: "10–30", flag: null, unit: "mg/dL" },
    ],
  },
  {
    id: "LAB-2026-8790",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    test: "Chest Radiography (PA View)",
    category: "Radiology",
    date: "Aug 22, 2026",
    status: "Ready",
    specimenType: "Digital Radiograph",
    orderingPhysician: "Dr. Jose Reyes, MD",
    releasedBy: "Dr. Roberto Silva, MD (Radiology)",
    summary: "Clear lung parenchymal fields. Heart size within normal limits (CTR < 0.50). Bilateral costophrenic angles sharp.",
    items: [
      { name: "Cardiothoracic Ratio", value: "0.48", ref: "< 0.50", flag: null },
      { name: "Pulmonary Vasculature", value: "Normal", ref: "Normal", flag: null },
      { name: "Pleural Spaces", value: "No effusion", ref: "No effusion", flag: null },
      { name: "Bony Cage / Ribs", value: "Intact", ref: "Intact", flag: null },
    ],
  },
  {
    id: "LAB-2026-8910",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    test: "Stat CBC & Abdominal Ultrasound",
    category: "Hematology",
    date: "Sep 11, 2026",
    status: "Ready",
    specimenType: "Whole Blood & Sonogram",
    orderingPhysician: "Dr. Jose Reyes, MD",
    releasedBy: "Jumie Palma, RMT",
    summary: "Significant leukocytosis with neutrophil shift. Non-compressible aperistaltic tubular structure at RLQ measuring 8.2mm.",
    items: [
      { name: "White Blood Cells (WBC)", value: "14.5 × 10³/μL", ref: "4.5–11.0", flag: "H", unit: "× 10³/μL" },
      { name: "Neutrophils %", value: "84%", ref: "50–70", flag: "H", unit: "%" },
      { name: "Appendix Diameter", value: "8.2 mm", ref: "< 6.0 mm", flag: "H", unit: "mm" },
    ],
  },
];

export const INITIAL_MEDICATIONS: MedicationOrder[] = [
  {
    id: "MED-001",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Amlodipine Besylate",
    dose: "5 mg",
    route: "Oral (PO)",
    freq: "Once daily, morning",
    start: "Jan 15, 2024",
    prescribedBy: "Dr. Jose Reyes, MD",
    status: "Active",
    refillable: true,
    refillStatus: "Not Requested",
    lastAdministered: "Today, 08:00 AM",
    administeredBy: "Patient self-administered",
    notes: "Monitor for peripheral edema.",
  },
  {
    id: "MED-002",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Losartan Potassium",
    dose: "50 mg",
    route: "Oral (PO)",
    freq: "Once daily, morning",
    start: "Jan 15, 2024",
    prescribedBy: "Dr. Jose Reyes, MD",
    status: "Active",
    refillable: true,
    refillStatus: "Not Requested",
    lastAdministered: "Today, 08:00 AM",
    administeredBy: "Patient self-administered",
    notes: "Take with or without food.",
  },
  {
    id: "MED-003",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Atorvastatin Calcium",
    dose: "20 mg",
    route: "Oral (PO)",
    freq: "Once daily, at bedtime",
    start: "Sep 10, 2026",
    prescribedBy: "Dr. Jose Reyes, MD",
    status: "Active",
    refillable: true,
    refillStatus: "Pending Approval",
    lastAdministered: "Yesterday, 09:30 PM",
    administeredBy: "Patient self-administered",
    notes: "Liver enzyme monitoring in 6 months.",
  },
  {
    id: "MED-004",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Aspirin (Enteric Coated)",
    dose: "80 mg",
    route: "Oral (PO)",
    freq: "Once daily, after breakfast",
    start: "Mar 03, 2024",
    prescribedBy: "Dr. Jose Reyes, MD",
    status: "Active",
    refillable: false,
    refillStatus: "Not Requested",
    lastAdministered: "Today, 08:30 AM",
    administeredBy: "Patient self-administered",
    notes: "Take strictly with a full glass of water after food.",
  },
  {
    id: "MED-005",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    name: "Ceftriaxone IV",
    dose: "1 g",
    route: "Intravenous (IVPB)",
    freq: "Every 24 hours",
    start: "Sep 11, 2026",
    prescribedBy: "Dr. Jose Reyes, MD",
    status: "Active",
    refillable: false,
    lastAdministered: "Today, 06:00 AM",
    administeredBy: "Angel Mae, RN",
    notes: "Inpatient piggyback over 30 mins.",
  },
];

export const INITIAL_TREATMENTS: TreatmentLog[] = [
  {
    id: "TRT-001",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    timestamp: "2026-09-10 10:15",
    treatmentName: "Blood Pressure & Pulse Oximetry Assessment",
    category: "Bedside Nursing",
    performedBy: "Angel Mae, RN",
    role: "Nurse",
    vitalsAtTreatment: "BP 145/92 mmHg, HR 82 bpm, SpO2 99%",
    notes: "Patient seated resting for 10 minutes prior to measurement. Educated on home BP log.",
  },
  {
    id: "TRT-002",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    timestamp: "2026-09-11 15:00",
    treatmentName: "Peripheral IV Cannulation (Gauge 18, Left Forearm)",
    category: "IV Therapy",
    performedBy: "Angel Mae, RN",
    role: "Nurse",
    vitalsAtTreatment: "BP 130/85, HR 96 bpm",
    notes: "Aseptic technique maintained. Free blood return confirmed, flushed with Normal Saline. IV infusion started.",
  },
  {
    id: "TRT-003",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    timestamp: "2026-09-12 08:30",
    treatmentName: "Oxygen Cannula Titration & Deep Breathing Exercise",
    category: "Respiratory Therapy",
    performedBy: "Angel Mae, RN",
    role: "Nurse",
    vitalsAtTreatment: "SpO2 improved from 92% to 97% on 2 LPM via nasal cannula",
    notes: "Patient tolerated breathing exercises well. Semi-Fowler's position maintained.",
  },
];

export const INITIAL_ADMISSIONS: AdmissionEntry[] = [
  {
    id: "ADM-2026-014",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    admissionDate: "2026-09-11 14:30",
    ward: "Surgical Ward (3rd Floor)",
    bed: "Bed 204-A",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admittingStaff: "Jendy Perez (Admissions)",
    reason: "Acute Abdomen / Acute Appendicitis for Laparoscopic Appendectomy",
    status: "Admitted",
  },
  {
    id: "ADM-2026-012",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    admissionDate: "2026-09-09 09:15",
    ward: "Medical Ward (4th Floor)",
    bed: "Bed 312-B",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admittingStaff: "Jendy Perez (Admissions)",
    reason: "Congestive Heart Failure exacerbation, bilateral pleural effusion",
    status: "Admitted",
  },
  {
    id: "ADM-2026-015",
    patientId: "P-2024-004",
    patientName: "Eduardo Mendoza",
    admissionDate: "2026-09-12 06:45",
    ward: "Emergency Observation Unit",
    bed: "Bed ER-03",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admittingStaff: "Jendy Perez (Admissions)",
    reason: "Motorcycle accident trauma surveillance; stable vitals",
    status: "Observation",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "AUD-991",
    timestamp: "2026-09-12 11:42:10",
    userName: "Dr. Jose Reyes, MD",
    userRole: "doctor",
    action: "EHR Record Consultation & Clinical Note Created",
    targetPatient: "Maria Santos",
    patientId: "P-2024-001",
    department: "Internal Medicine & OPD",
    ipAddress: "192.168.10.45",
    status: "Authorized",
  },
  {
    id: "AUD-990",
    timestamp: "2026-09-12 10:15:33",
    userName: "Angel Mae, RN",
    userRole: "nurse",
    action: "Medication Administration & Vitals Logged (MAR)",
    targetPatient: "Carlos Dela Cruz",
    patientId: "P-2024-002",
    department: "Surgical Ward",
    ipAddress: "192.168.10.82",
    status: "Authorized",
  },
  {
    id: "AUD-989",
    timestamp: "2026-09-12 08:30:19",
    userName: "Jendy Perez",
    userRole: "staff",
    action: "Patient Registration & Bed Allocation Completed",
    targetPatient: "Eduardo Mendoza",
    patientId: "P-2024-004",
    department: "Admissions Desk",
    ipAddress: "192.168.10.12",
    status: "Authorized",
  },
  {
    id: "AUD-988",
    timestamp: "2026-09-11 16:20:05",
    userName: "Maria Santos",
    userRole: "patient",
    action: "Patient Portal Login & Lab Result Retrieval (CBC, Lipid)",
    targetPatient: "Maria Santos",
    patientId: "P-2024-001",
    department: "Patient Self-Service Portal",
    ipAddress: "112.198.110.24",
    status: "Authorized",
  },
  {
    id: "AUD-987",
    timestamp: "2026-09-11 14:05:44",
    userName: "Atty. Roberto Ramos",
    userRole: "admin",
    action: "DPA 2012 Compliance Audit & Access Verification Run",
    targetPatient: "System Wide",
    patientId: "ALL-RECORDS",
    department: "Data Privacy & Compliance",
    ipAddress: "192.168.10.5",
    status: "Authorized",
  },
];
