import {
  User,
  Patient,
  HealthRecord,
  DiagnosticResult,
  MedicationOrder,
  TreatmentLog,
  AdmissionEntry,
  AuditLog,
  VisitorLog,
  ShiftEndorsement,
  HospitalConfig,
  OpdQueueItem,
  PhilHealthClaim,
  OpdReferral,
  OpdDischarge,
} from "./types";

export const INITIAL_HOSPITAL_CONFIG: HospitalConfig = {
  name: "CarePoint Medical Center",
  tagline: "Compassionate Care. Trusted Service. Better Health.",
  logoText: "CarePoint Medical Center",
  phone: "(02) 8920-5000",
  emergencyHotline: "911",
  email: "care@carepointmedical.ph",
  dpoEmail: "dpo@carepointmedical.ph",
  address: "CarePoint Complex, National Highway, Metro Manila, Philippines",
  accreditation: "DOH Licensed Outpatient Healthcare Facility | PhilHealth Accredited",
};

export const HEALTHCARE_TEAM_DIRECTORY = [
  { name: "Dr. Mark Arkiel Jacobe", position: "Founder & Medical Director", role: "doctor" as const, license: "PRC Lic. #0089201", credentials: "MD, FACP (Internal Medicine)", color: "bg-blue-600", department: "Executive Medical Directorate" },
  { name: "Dr. Roldan Bidar", position: "Attending Physician", role: "doctor" as const, license: "PRC Lic. #0091442", credentials: "MD, FPCP (Family & Adult Medicine)", color: "bg-blue-700", department: "Outpatient Department" },
  { name: "JP Valebia", position: "Hospital Administrator", role: "admin" as const, license: "HA-PRC #1002", credentials: "MHA, CHA", color: "bg-amber-600", department: "Hospital Administration" },
  { name: "Nurse Angelmae Palma, RN", position: "Head Nurse", role: "nurse" as const, license: "PRC Lic. #0093820", credentials: "RN, MAN, CCRN", color: "bg-teal-600", department: "Nursing & Triage Station" },
  { name: "Nurse Rechel Ann Perez, RN", position: "Staff Nurse", role: "nurse" as const, license: "PRC Lic. #0096211", credentials: "RN, BSN", color: "bg-teal-700", department: "Ward & Bedside Care" },
  { name: "Angel Bellen, RMT", position: "Medical Technologist", role: "staff" as const, license: "PRC Lic. #0054112", credentials: "RMT, AMT", color: "bg-purple-600", department: "Clinical Diagnostic Laboratory" },
  { name: "Emman Garlitos", position: "Healthcare Assistant", role: "staff" as const, license: "EMP-HA-008", credentials: "CHA, NC-II", color: "bg-slate-600", department: "Clinical Support Services" },
  { name: "Arabella Salazar", position: "Patient Services Coordinator", role: "staff" as const, license: "EMP-PSC-012", credentials: "BSHM, CHIO", color: "bg-emerald-600", department: "Patient Admissions & Care" },
  { name: "Jessa May Angelia", position: "Legal Counsel & DPO", role: "admin" as const, license: "IBP Roll #54219", credentials: "JD, CIPP/A", color: "bg-amber-700", department: "Legal Compliance & Privacy" },
  { name: "Glenda Llarvez", position: "Front Desk Receptionist", role: "staff" as const, license: "EMP-REC-005", credentials: "BA Communication", color: "bg-emerald-700", department: "Front Desk & Admissions" },
  { name: "Jessa May Dagami", position: "Chief Financial Officer", role: "admin" as const, license: "CPA Lic. #0077421", credentials: "CPA, MBA", color: "bg-indigo-600", department: "Finance & Accounting" },
  { name: "Rose Jane Gorospe", position: "Pharmacy Technician", role: "staff" as const, license: "PRC Lic. #0033190", credentials: "CPhT, BSP", color: "bg-rose-600", department: "Outpatient Pharmacy" },
];

export const DEMO_USERS: Record<string, { password: string; user: User }> = {
  "dr.jacobe": {
    password: "pass",
    user: {
      id: "D-001",
      name: "Dr. Mark Arkiel Jacobe",
      username: "dr.jacobe",
      role: "doctor",
      title: "Founder & Medical Director",
      department: "Executive Medical Directorate",
      avatarInitials: "MJ",
      licenseNumber: "PRC Lic. #0089201",
      credentials: "MD, FACP (Internal Medicine)",
      status: "active",
      contactEmail: "m.jacobe@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 101",
    },
  },
  "dr.bidar": {
    password: "pass",
    user: {
      id: "D-002",
      name: "Dr. Roldan Bidar",
      username: "dr.bidar",
      role: "doctor",
      title: "Attending Physician",
      department: "Outpatient Department",
      avatarInitials: "RB",
      licenseNumber: "PRC Lic. #0091442",
      credentials: "MD, FPCP (Family & Adult Medicine)",
      status: "active",
      contactEmail: "r.bidar@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 201",
    },
  },
  "nurse.palma": {
    password: "pass",
    user: {
      id: "N-001",
      name: "Nurse Angelmae Palma, RN",
      username: "nurse.palma",
      role: "nurse",
      title: "Head Nurse",
      department: "Nursing & Triage Station",
      avatarInitials: "AP",
      licenseNumber: "PRC Lic. #0093820",
      credentials: "RN, MAN, CCRN",
      status: "active",
      contactEmail: "a.palma@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 301",
    },
  },
  "nurse.perez": {
    password: "pass",
    user: {
      id: "N-002",
      name: "Nurse Rechel Ann Perez, RN",
      username: "nurse.perez",
      role: "nurse",
      title: "Staff Nurse",
      department: "Ward & Bedside Care",
      avatarInitials: "RP",
      licenseNumber: "PRC Lic. #0096211",
      credentials: "RN, BSN",
      status: "active",
      contactEmail: "r.perez@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 302",
    },
  },
  "staff.glenda": {
    password: "pass",
    user: {
      id: "S-101",
      name: "Glenda Llarvez",
      username: "staff.glenda",
      role: "staff",
      title: "Front Desk Receptionist",
      department: "Front Desk & Admissions",
      avatarInitials: "GL",
      licenseNumber: "EMP-REC-005",
      credentials: "BA Communication",
      status: "active",
      contactEmail: "g.llarvez@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 100",
    },
  },
  "staff.arabella": {
    password: "pass",
    user: {
      id: "S-102",
      name: "Arabella Salazar",
      username: "staff.arabella",
      role: "staff",
      title: "Patient Services Coordinator",
      department: "Patient Admissions & Care",
      avatarInitials: "AS",
      licenseNumber: "EMP-PSC-012",
      credentials: "BSHM, CHIO",
      status: "active",
      contactEmail: "a.salazar@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 102",
    },
  },
  "admin.jp": {
    password: "pass",
    user: {
      id: "A-001",
      name: "JP Valebia",
      username: "admin.jp",
      role: "admin",
      title: "Hospital Administrator",
      department: "Hospital Administration",
      avatarInitials: "JV",
      licenseNumber: "HA-PRC #1002",
      credentials: "MHA, CHA",
      status: "active",
      contactEmail: "jp.valebia@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 901",
    },
  },
  "admin.jessa": {
    password: "pass",
    user: {
      id: "A-002",
      name: "Jessa May Angelia",
      username: "admin.jessa",
      role: "admin",
      title: "Legal Counsel & DPO",
      department: "Legal Compliance & Privacy",
      avatarInitials: "JA",
      licenseNumber: "IBP Roll #54219",
      credentials: "JD, CIPP/A",
      status: "active",
      contactEmail: "dpo@carepointmedical.ph",
      contactPhone: "+63 (2) 8920-5000 ext. 902",
    },
  },
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "P-2024-001",
    name: "Maria Santos",
    dob: "1992-04-14",
    age: 34,
    gender: "Female",
    civilStatus: "Married",
    contact: "0917-555-1234",
    address: "Block 14 Lot 3, Acacia St., San Antonio, Pasig City",
    emergencyContact: {
      name: "Juan Santos",
      relationship: "Spouse",
      phone: "0918-444-9876",
    },
    bloodType: "O+",
    allergies: ["Penicillin", "NSAIDs"],
    chiefComplaint: "Periodic elevated blood pressure readings and mild occipital headaches.",
    triageTier: "stable",
    triageReason: "Stage 1 Essential Hypertension; hemodynamically stable; asymptomatic dyslipidemia.",
    admissionStatus: "Outpatient",
    ward: "OPD Clinic 3",
    bed: "Chair 04",
    attendingPhysician: "Dr. Jose Reyes, MD",
    registeredAt: "2024-01-12",
    philhealth: {
      pin: "12-054918234-1",
      category: "Direct Contributor - Private",
      eligibilityStatus: "Active / Eligible",
      coverageDetails: "Primary Care Benefit + OPD Diagnostic Case Rates Active (PhilHealth Konsulta)",
    },
    consents: {
      treatmentCareConsent: true,
      healthInfoSharingConsent: true,
      contactNoticeConsent: true,
      signedDate: "2026-09-10",
      witnessStaff: "Jendy Perez (EMP-ADM-101)",
    },
    medicalHistory: {
      pastMedical: ["Mild Gestational Hypertension (2020)", "Dyslipidemia (2023)"],
      pastSurgical: ["Cesarean Section (2020)"],
      familyHistory: ["Hypertension (Maternal)", "Type 2 Diabetes (Paternal)"],
      chronicConditions: ["Essential Hypertension - Stage 1"],
    },
  },
  {
    id: "P-2024-002",
    name: "Carlos Dela Cruz",
    dob: "1978-08-20",
    age: 48,
    gender: "Male",
    civilStatus: "Married",
    contact: "0920-888-4321",
    address: "24 Mahogany Lane, Greenhills, San Juan City",
    emergencyContact: {
      name: "Elena Dela Cruz",
      relationship: "Spouse",
      phone: "0921-777-6543",
    },
    bloodType: "A+",
    allergies: ["Sulfa drugs"],
    chiefComplaint: "Acute abdominal pain, right lower quadrant tenderness with fever (38.2°C).",
    triageTier: "critical",
    triageReason: "Acute Appendicitis with localized peritonitis risk; fever 38.2°C, leukocytosis 14.5k.",
    admissionStatus: "Admitted",
    ward: "Surgical Ward",
    bed: "Bed 204-A",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admissionDate: "2026-09-11 14:30",
    registeredAt: "2024-03-05",
    philhealth: {
      pin: "08-119482015-7",
      category: "Direct Contributor - Private",
      eligibilityStatus: "Active / Eligible",
      coverageDetails: "All-Case Rate Qualified: Appendectomy Code 44950 (₱24,000 package allowance)",
    },
    consents: {
      treatmentCareConsent: true,
      healthInfoSharingConsent: true,
      contactNoticeConsent: true,
      signedDate: "2026-09-11",
      witnessStaff: "Jendy Perez (EMP-ADM-101)",
    },
    medicalHistory: {
      pastMedical: ["Gastritis (2021)"],
      pastSurgical: ["None"],
      familyHistory: ["Colorectal Polyp (Sibling)"],
      chronicConditions: ["None reported"],
    },
  },
  {
    id: "P-2024-003",
    name: "Luzviminda Garcia",
    dob: "1960-11-03",
    age: 65,
    gender: "Female",
    civilStatus: "Widowed",
    contact: "0919-333-7711",
    address: "78 Rosal St., Barangay Kapitolyo, Pasig City",
    emergencyContact: {
      name: "Mark Garcia",
      relationship: "Son",
      phone: "0919-222-8844",
    },
    bloodType: "B+",
    allergies: ["Latex", "Aspirin"],
    chiefComplaint: "Shortness of breath on exertion and bilateral lower extremity edema.",
    triageTier: "observation",
    triageReason: "CHF Exacerbation; requires strict fluid balance charting and SpO2 surveillance.",
    admissionStatus: "Admitted",
    ward: "Medical Ward",
    bed: "Bed 312-B",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admissionDate: "2026-09-09 09:15",
    registeredAt: "2023-08-19",
    philhealth: {
      pin: "03-294810239-0",
      category: "Senior Citizen (RA 10645)",
      eligibilityStatus: "Active / Eligible",
      coverageDetails: "Mandatory Senior Citizen Full Coverage | Case Rate Code: Heart Failure 428.0 (₱15,700)",
    },
    consents: {
      treatmentCareConsent: true,
      healthInfoSharingConsent: true,
      contactNoticeConsent: true,
      signedDate: "2026-09-09",
      witnessStaff: "Jendy Perez (EMP-ADM-101)",
    },
    medicalHistory: {
      pastMedical: ["Congestive Heart Failure NYHA II", "Coronary Artery Disease"],
      pastSurgical: ["Percutaneous Coronary Intervention (2018)"],
      familyHistory: ["Ischemic Heart Disease (Both parents)"],
      chronicConditions: ["Chronic Systolic Heart Failure", "Hyperuricemia"],
    },
  },
  {
    id: "P-2024-004",
    name: "Eduardo Mendoza",
    dob: "2001-02-18",
    age: 25,
    gender: "Male",
    civilStatus: "Single",
    contact: "0932-111-9900",
    address: "15 Dahlia St., Mandaluyong City",
    emergencyContact: {
      name: "Carmela Mendoza",
      relationship: "Mother",
      phone: "0932-555-6677",
    },
    bloodType: "O-",
    allergies: ["None known"],
    chiefComplaint: "Blunt chest trauma following motorcycle fall. Hemodynamically stable.",
    triageTier: "observation",
    triageReason: "Post-trauma surveillance: Serial rib X-ray and thoracic auscultation monitoring.",
    admissionStatus: "Observation",
    ward: "Emergency Observation",
    bed: "Bed ER-03",
    attendingPhysician: "Dr. Jose Reyes, MD",
    admissionDate: "2026-09-12 06:45",
    registeredAt: "2026-09-12",
    philhealth: {
      pin: "19-482019482-3",
      category: "Indirect Contributor - Indigent",
      eligibilityStatus: "Sponsored (Indigent)",
      coverageDetails: "No Balance Billing (NBB) Eligible - Point of Service (POS) Program",
    },
    consents: {
      treatmentCareConsent: true,
      healthInfoSharingConsent: true,
      contactNoticeConsent: true,
      signedDate: "2026-09-12",
      witnessStaff: "Jendy Perez (EMP-ADM-101)",
    },
    medicalHistory: {
      pastMedical: ["None"],
      pastSurgical: ["None"],
      familyHistory: ["None known"],
      chronicConditions: ["None"],
    },
  },
];

export const INITIAL_OPD_QUEUE: OpdQueueItem[] = [
  {
    id: "Q-01",
    queueNumber: 1,
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    age: 48,
    gender: "Male",
    triageTier: "critical",
    checkInTime: "08:15 AM",
    chiefComplaint: "Severe RLQ abdominal tenderness with fever (38.2°C)",
    assignedDoctor: "Dr. Jose Reyes, MD",
    status: "In-Consultation",
    roomOrBooth: "Consultation Room 1",
  },
  {
    id: "Q-02",
    queueNumber: 2,
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    age: 65,
    gender: "Female",
    triageTier: "observation",
    checkInTime: "08:30 AM",
    chiefComplaint: "Shortness of breath on exertion, bilateral pedal edema",
    assignedDoctor: "Dr. Jose Reyes, MD",
    status: "Waiting",
    roomOrBooth: "Waiting Lounge A",
  },
  {
    id: "Q-03",
    queueNumber: 3,
    patientId: "P-2024-004",
    patientName: "Eduardo Mendoza",
    age: 25,
    gender: "Male",
    triageTier: "observation",
    checkInTime: "08:45 AM",
    chiefComplaint: "Blunt chest wall pain after motorcycle fall",
    assignedDoctor: "Dr. Jose Reyes, MD",
    status: "Waiting",
    roomOrBooth: "Waiting Lounge A",
  },
  {
    id: "Q-04",
    queueNumber: 4,
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    age: 34,
    gender: "Female",
    triageTier: "stable",
    checkInTime: "09:00 AM",
    chiefComplaint: "Periodic elevated blood pressure readings and mild headaches",
    assignedDoctor: "Dr. Jose Reyes, MD",
    status: "Waiting",
    roomOrBooth: "Waiting Lounge B",
  },
];

export const INITIAL_PHILHEALTH_CLAIMS: PhilHealthClaim[] = [
  {
    id: "CLM-2026-001",
    patientId: "P-2024-002",
    pin: "08-119482015-7",
    memberName: "Dela Cruz, Carlos M.",
    membershipType: "Formal Economy / Private",
    diagnosisWithIcd: "Acute Appendicitis - ICD-10: K35.80",
    caseRateAmount: "Php 24,000 - Surgical Package",
    claimStatus: "Ready for Submission",
    submissionDate: "2026-09-14",
    hospitalCharges: 38500,
    philhealthBenefit: 24000,
    patientPayable: 14500,
  },
  {
    id: "CLM-2026-002",
    patientId: "P-2024-003",
    pin: "03-294810239-0",
    memberName: "Garcia, Luzviminda T.",
    membershipType: "Senior Citizen (RA 10645)",
    diagnosisWithIcd: "Congestive Heart Failure - ICD-10: I50.9",
    caseRateAmount: "Php 15,700 - Medical Case",
    claimStatus: "Transmitted",
    submissionDate: "2026-09-12",
    hospitalCharges: 22000,
    philhealthBenefit: 15700,
    patientPayable: 6300,
  },
  {
    id: "CLM-2026-003",
    patientId: "P-2024-004",
    pin: "19-482019482-3",
    memberName: "Mendoza, Eduardo P.",
    membershipType: "Indigent / NHTS-PR (NBB Eligible)",
    diagnosisWithIcd: "Blunt Thoracic Trauma - ICD-10: S29.9",
    caseRateAmount: "Php 11,200 - Trauma Case",
    claimStatus: "Under Adjudication",
    submissionDate: "2026-09-13",
    hospitalCharges: 11200,
    philhealthBenefit: 11200,
    patientPayable: 0,
  },
  {
    id: "CLM-2026-004",
    patientId: "P-2024-001",
    pin: "12-054918234-1",
    memberName: "Santos, Maria Elena",
    membershipType: "Formal Economy / Private",
    diagnosisWithIcd: "Essential Hypertension Stage 1 - ICD-10: I10",
    caseRateAmount: "Php 9,000 - OPD Konsulta Package",
    claimStatus: "Approved / Reimbursed",
    submissionDate: "2026-09-10",
    hospitalCharges: 10500,
    philhealthBenefit: 9000,
    patientPayable: 1500,
  },
  {
    id: "CLM-2026-005",
    patientId: "P-2026-005",
    pin: "15-884920184-4",
    memberName: "Tan, Juanito Bautista",
    membershipType: "Self-Employed / Professional",
    diagnosisWithIcd: "Acute Gastroenteritis - ICD-10: A09",
    caseRateAmount: "Php 6,000 - Medical Case",
    claimStatus: "Ready for Submission",
    submissionDate: "2026-09-14",
    hospitalCharges: 8500,
    philhealthBenefit: 6000,
    patientPayable: 2500,
  },
];

export const INITIAL_OPD_REFERRALS: OpdReferral[] = [
  {
    id: "REF-001",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    referredFrom: "Outpatient Triage Clinic",
    referredTo: "General Surgery Department & Inpatient OR",
    reason: "Stat pre-operative surgical assessment for acute appendicitis",
    priority: "Stat Emergency",
    timestamp: "2026-09-14 08:45 AM",
    referringDoctor: "Dr. Jose Reyes, MD",
    status: "Accepted",
  },
  {
    id: "REF-002",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    referredFrom: "Internal Medicine OPD",
    referredTo: "Cardiology Echocardiography Lab",
    reason: "2D-Echocardiogram with Doppler for ejection fraction evaluation",
    priority: "Urgent",
    timestamp: "2026-09-14 09:15 AM",
    referringDoctor: "Dr. Jose Reyes, MD",
    status: "Pending",
  },
];

export const INITIAL_OPD_DISCHARGES: OpdDischarge[] = [
  {
    id: "DISC-001",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    dischargeDate: "2026-09-14 10:30 AM",
    disposition: "Follow-up Scheduled",
    followUpDate: "2026-09-28 (2 Weeks)",
    instructions: "Continue Amlodipine 5mg OD, maintain low-sodium diet (<2g/day). Keep daily morning BP log.",
    clearedByDoctor: "Dr. Jose Reyes, MD (PRC Lic. #0084721)",
  },
];

export const ICD10_CATALOG = [
  { code: "I10", name: "Essential (primary) hypertension", category: "Cardiovascular" },
  { code: "K35.80", name: "Acute appendicitis, unspecified", category: "Gastrointestinal" },
  { code: "I50.9", name: "Heart failure, unspecified", category: "Cardiovascular" },
  { code: "A09", name: "Infectious gastroenteritis and colitis", category: "Infectious" },
  { code: "E78.0", name: "Pure hypercholesterolemia", category: "Endocrine/Metabolic" },
  { code: "E11.9", name: "Type 2 diabetes mellitus without complications", category: "Endocrine/Metabolic" },
  { code: "J06.9", name: "Acute upper respiratory infection, unspecified", category: "Respiratory" },
  { code: "S29.9", name: "Unspecified injury of thorax", category: "Trauma" },
  { code: "M54.5", name: "Low back pain", category: "Musculoskeletal" },
  { code: "R51", name: "Headache, unspecified", category: "Neurology" },
];

export const INITIAL_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: "EHR-2026-0910",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    date: "September 10, 2026",
    type: "OPD Visit",
    doctor: "Dr. Jose Reyes, MD",
    doctorLicense: "PRC Lic. #0084721",
    diagnosis: "Essential Hypertension — Stage 1",
    icd10Code: "I10",
    differentialDiagnosis: ["White-coat Hypertension", "Renal Artery Stenosis (Excluded)"],
    subjective: "Patient reports occasional morning headaches and neck stiffness over past 2 weeks. Complies with low-salt diet mostly, denies chest pain or visual changes.",
    objective: "Alert, oriented x3, ambulatory without distress. Regular S1/S2 heart sounds, no murmurs. Lungs clear to auscultation bilaterally. BMI: 25.6 kg/m².",
    assessment: "Controlled Stage 1 Essential Hypertension with mild transient elevation; asymptomatic dyslipidemia.",
    plan: "Continue Amlodipine 5mg once daily; initiate Atorvastatin 20mg bedtime. Low sodium counseling (<2g/day). Follow up in 2 weeks with home BP log.",
    notes: "Patient advised to maintain daily blood pressure log in morning and evening.",
    internalClinicianNotes: "CONFIDENTIAL CLINICAL IMPRESSION: Patient exhibits compliance hesitation with statin therapy. Screen for familial hypercholesterolemia.",
    vitals: {
      bp: "145/92 mmHg",
      hr: "82 bpm",
      temp: "36.8°C",
      wt: "68 kg",
      spo2: "99%",
      rr: "16 cpm",
      height: "163 cm",
      bmi: "25.6",
      bmiCategory: "Overweight",
      systolic: 145,
      diastolic: 92,
      fluidIntakeMl: 1500,
      urineOutputMl: 1300,
    },
  },
  {
    id: "EHR-2026-0911",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    date: "September 11, 2026",
    type: "Inpatient Progress",
    doctor: "Dr. Jose Reyes, MD",
    doctorLicense: "PRC Lic. #0084721",
    diagnosis: "Acute Appendicitis — Early Catarrhal",
    icd10Code: "K35.80",
    differentialDiagnosis: ["Mesenteric Adenitis", "Urolithiasis"],
    subjective: "Patient admitted through ER with periumbilical pain migrating to right iliac fossa, anorexia and low-grade pyrexia.",
    objective: "McBurney's point tenderness positive, Rovsing's sign positive. Guarding noted. WBC 14.5 x 10^3/uL. Temp 38.2°C.",
    assessment: "Acute uncomplicated appendicitis with localized peritoneal irritation.",
    plan: "NPO order, IV Ceftriaxone 1g q24h + Metronidazole 500mg q8h. Pre-operative surgical consult called.",
    notes: "Consent for exploratory laparotomy / laparoscopic appendectomy obtained.",
    vitals: {
      bp: "130/85 mmHg",
      hr: "96 bpm",
      temp: "38.2°C",
      wt: "74 kg",
      spo2: "98%",
      rr: "20 cpm",
      height: "172 cm",
      bmi: "25.0",
      bmiCategory: "Normal",
      systolic: 130,
      diastolic: 85,
      fluidIntakeMl: 2000,
      urineOutputMl: 1100,
    },
  },
];

export const INITIAL_LAB_RESULTS: DiagnosticResult[] = [
  {
    id: "LAB-2026-8801",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    test: "Complete Blood Count (CBC) with Platelets",
    category: "Hematology",
    date: "Sep 10, 2026",
    status: "Ready",
    specimenType: "Whole Blood (EDTA)",
    orderingPhysician: "Dr. Jose Reyes, MD",
    orderingPhysicianLicense: "PRC Lic. #0084721",
    releasedBy: "Jumie Palma, RMT (PRC Lic. #0044812)",
    summary: "All hematological indices are within acceptable physiological limits. No leukocytosis or thrombocytopenia.",
    items: [
      { name: "Hemoglobin", value: "13.8 g/dL", ref: "12.0–16.0", flag: null, unit: "g/dL" },
      { name: "White Blood Cells (WBC)", value: "7.2 × 10³/μL", ref: "4.5–11.0", flag: null, unit: "× 10³/μL" },
      { name: "Platelet Count", value: "210 × 10³/μL", ref: "150–400", flag: null, unit: "× 10³/μL" },
      { name: "Hematocrit (PCV)", value: "42.0%", ref: "37.0–48.0", flag: null, unit: "%" },
      { name: "Neutrophils", value: "62%", ref: "50–70", flag: null, unit: "%" },
      { name: "Lymphocytes", value: "31%", ref: "20–40", flag: null, unit: "%" },
    ],
  },
  {
    id: "LAB-2026-8802",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    test: "Fasting Lipid Profile",
    category: "Clinical Chemistry",
    date: "Sep 10, 2026",
    status: "Ready",
    specimenType: "Serum (12-hour fast)",
    orderingPhysician: "Dr. Jose Reyes, MD",
    orderingPhysicianLicense: "PRC Lic. #0084721",
    releasedBy: "Jumie Palma, RMT (PRC Lic. #0044812)",
    summary: "Mild elevation noted in Total Cholesterol and LDL fraction. Follow-up statin therapy indicated.",
    items: [
      { name: "Total Cholesterol", value: "215 mg/dL", ref: "< 200", flag: "H", unit: "mg/dL" },
      { name: "LDL Direct Cholesterol", value: "148 mg/dL", ref: "< 100", flag: "H", unit: "mg/dL" },
      { name: "HDL Good Cholesterol", value: "52 mg/dL", ref: "> 50", flag: null, unit: "mg/dL" },
      { name: "Triglycerides", value: "138 mg/dL", ref: "< 150", flag: null, unit: "mg/dL" },
      { name: "VLDL Cholesterol", value: "27.6 mg/dL", ref: "10–30", flag: null, unit: "mg/dL" },
    ],
  },
  {
    id: "LAB-2026-8910",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    test: "Stat CBC & Abdominal Ultrasound",
    category: "Hematology",
    date: "Sep 11, 2026",
    status: "Ready",
    specimenType: "Whole Blood & Sonogram",
    orderingPhysician: "Dr. Jose Reyes, MD",
    orderingPhysicianLicense: "PRC Lic. #0084721",
    releasedBy: "Jumie Palma, RMT (PRC Lic. #0044812)",
    summary: "Significant leukocytosis with neutrophil shift. Non-compressible aperistaltic tubular structure at RLQ measuring 8.2mm.",
    items: [
      { name: "White Blood Cells (WBC)", value: "14.5 × 10³/μL", ref: "4.5–11.0", flag: "H", unit: "× 10³/μL" },
      { name: "Neutrophils %", value: "84%", ref: "50–70", flag: "H", unit: "%" },
      { name: "Appendix Diameter", value: "8.2 mm", ref: "< 6.0 mm", flag: "H", unit: "mm" },
    ],
  },
];

export const INITIAL_MEDICATIONS: MedicationOrder[] = [
  {
    id: "MED-001",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Amlodipine Besylate",
    dose: "5 mg",
    route: "Oral (PO)",
    freq: "Once daily, morning",
    start: "Jan 15, 2024",
    prescribedBy: "Dr. Jose Reyes, MD",
    prescribedByLicense: "PRC Lic. #0084721",
    status: "Active",
    refillable: true,
    refillStatus: "Not Requested",
    lastAdministered: "Today, 08:00 AM",
    administeredBy: "Angel Mae, RN",
    administeredByLicense: "PRC Lic. #0093820",
    notes: "Take with breakfast. Monitor for lower extremity edema.",
  },
  {
    id: "MED-002",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Losartan Potassium",
    dose: "50 mg",
    route: "Oral (PO)",
    freq: "Once daily, morning",
    start: "Jan 15, 2024",
    prescribedBy: "Dr. Jose Reyes, MD",
    prescribedByLicense: "PRC Lic. #0084721",
    status: "Active",
    refillable: true,
    refillStatus: "Not Requested",
    lastAdministered: "Today, 08:00 AM",
    administeredBy: "Angel Mae, RN",
    administeredByLicense: "PRC Lic. #0093820",
    notes: "Blood pressure surveillance daily.",
  },
  {
    id: "MED-003",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    name: "Atorvastatin Calcium",
    dose: "20 mg",
    route: "Oral (PO)",
    freq: "Once daily, bedtime",
    start: "Sep 10, 2026",
    prescribedBy: "Dr. Jose Reyes, MD",
    prescribedByLicense: "PRC Lic. #0084721",
    status: "Active",
    refillable: true,
    refillStatus: "Pending Approval",
    lastAdministered: "Yesterday, 09:30 PM",
    administeredBy: "Angel Mae, RN",
    administeredByLicense: "PRC Lic. #0093820",
    notes: "Liver enzyme monitoring recommended in 6 months.",
  },
  {
    id: "MED-005",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    name: "Ceftriaxone IV",
    dose: "1 g",
    route: "Intravenous (IVPB)",
    freq: "Every 24 hours",
    start: "Sep 11, 2026",
    prescribedBy: "Dr. Jose Reyes, MD",
    prescribedByLicense: "PRC Lic. #0084721",
    status: "Active",
    refillable: false,
    lastAdministered: "Today, 06:00 AM",
    administeredBy: "Angel Mae, RN",
    administeredByLicense: "PRC Lic. #0093820",
    notes: "Inpatient piggyback over 30 mins with NS flush.",
  },
  {
    id: "MED-006",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    name: "Furosemide IV",
    dose: "40 mg",
    route: "Intravenous (IV Push)",
    freq: "Every 12 hours",
    start: "Sep 09, 2026",
    prescribedBy: "Dr. Jose Reyes, MD",
    prescribedByLicense: "PRC Lic. #0084721",
    status: "Active",
    refillable: false,
    lastAdministered: "Today, 07:00 AM",
    administeredBy: "Angel Mae, RN",
    administeredByLicense: "PRC Lic. #0093820",
    notes: "Slow push over 2 mins. Maintain strict urine output tracking.",
  },
];

export const INITIAL_TREATMENTS: TreatmentLog[] = [
  {
    id: "TRT-001",
    patientId: "P-2024-001",
    patientName: "Maria Santos",
    timestamp: "2026-09-10 10:15",
    treatmentName: "Blood Pressure & Comprehensive Vitals Assessment",
    category: "Bedside Nursing",
    performedBy: "Angel Mae, RN",
    performedByLicense: "PRC Lic. #0093820",
    role: "Senior Charge Nurse",
    vitalsAtTreatment: "BP 145/92 mmHg, HR 82 bpm, RR 16 cpm, SpO2 99%, Temp 36.8°C",
    structuredVitals: {
      systolicBp: 145,
      diastolicBp: 92,
      heartRate: 82,
      respiratoryRate: 16,
      spo2: 99,
      temperature: 36.8,
      heightCm: 163,
      weightKg: 68,
      bmi: 25.6,
      bmiCategory: "Overweight",
      fluidIntakeMl: 500,
      urineOutputMl: 450,
      recordedAt: "2026-09-10 10:15",
      recordedBy: "Angel Mae, RN (PRC Lic. #0093820)",
    },
    fluidIntakeMl: 500,
    urineOutputMl: 450,
    notes: "Patient rested for 10 minutes prior to measurement. Provided home BP diary guidance.",
  },
  {
    id: "TRT-002",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    timestamp: "2026-09-11 15:00",
    treatmentName: "Peripheral IV Cannulation (Gauge 18, Left Forearm) & Line Care",
    category: "IV Therapy",
    performedBy: "Angel Mae, RN",
    performedByLicense: "PRC Lic. #0093820",
    role: "Senior Charge Nurse",
    vitalsAtTreatment: "BP 130/85 mmHg, HR 96 bpm, RR 20 cpm, SpO2 98%, Temp 38.2°C",
    structuredVitals: {
      systolicBp: 130,
      diastolicBp: 85,
      heartRate: 96,
      respiratoryRate: 20,
      spo2: 98,
      temperature: 38.2,
      heightCm: 172,
      weightKg: 74,
      bmi: 25.0,
      bmiCategory: "Normal",
      fluidIntakeMl: 1000,
      urineOutputMl: 350,
      recordedAt: "2026-09-11 15:00",
      recordedBy: "Angel Mae, RN (PRC Lic. #0093820)",
    },
    fluidIntakeMl: 1000,
    urineOutputMl: 350,
    notes: "Aseptic technique maintained. Free blood flashback confirmed. Flushed with 5mL sterile NS. IV infusion commenced.",
  },
  {
    id: "TRT-003",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    timestamp: "2026-09-12 08:30",
    treatmentName: "Oxygen Cannula Titration & Fluid Charting Review",
    category: "Respiratory Therapy",
    performedBy: "Angel Mae, RN",
    performedByLicense: "PRC Lic. #0093820",
    role: "Senior Charge Nurse",
    vitalsAtTreatment: "BP 138/86 mmHg, HR 88 bpm, RR 18 cpm, SpO2 97% on 2 LPM, Temp 36.6°C",
    structuredVitals: {
      systolicBp: 138,
      diastolicBp: 86,
      heartRate: 88,
      respiratoryRate: 18,
      spo2: 97,
      temperature: 36.6,
      heightCm: 155,
      weightKg: 62,
      bmi: 25.8,
      bmiCategory: "Overweight",
      fluidIntakeMl: 400,
      urineOutputMl: 650,
      recordedAt: "2026-09-12 08:30",
      recordedBy: "Angel Mae, RN (PRC Lic. #0093820)",
    },
    fluidIntakeMl: 400,
    urineOutputMl: 650,
    notes: "Semi-Fowler's position maintained. Urine output positive following Furosemide dose. Dyspnea improved.",
  },
];

export const INITIAL_ADMISSIONS: AdmissionEntry[] = [
  {
    id: "ADM-2026-014",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    admissionDate: "2026-09-11 14:30",
    ward: "Surgical Ward (3rd Floor)",
    bed: "Bed 204-A",
    attendingPhysician: "Dr. Jose Reyes, MD",
    attendingPhysicianLicense: "PRC Lic. #0084721",
    admittingStaff: "Jendy Perez (EMP-ADM-101)",
    reason: "Acute Abdomen / Acute Appendicitis for Laparoscopic Appendectomy",
    triageTier: "critical",
    status: "Admitted",
  },
  {
    id: "ADM-2026-012",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    admissionDate: "2026-09-09 09:15",
    ward: "Medical Ward (4th Floor)",
    bed: "Bed 312-B",
    attendingPhysician: "Dr. Jose Reyes, MD",
    attendingPhysicianLicense: "PRC Lic. #0084721",
    admittingStaff: "Jendy Perez (EMP-ADM-101)",
    reason: "Congestive Heart Failure exacerbation, bilateral pleural effusion, fluid overload",
    triageTier: "observation",
    status: "Admitted",
  },
  {
    id: "ADM-2026-015",
    patientId: "P-2024-004",
    patientName: "Eduardo Mendoza",
    admissionDate: "2026-09-12 06:45",
    ward: "Emergency Observation Unit",
    bed: "Bed ER-03",
    attendingPhysician: "Dr. Jose Reyes, MD",
    attendingPhysicianLicense: "PRC Lic. #0084721",
    admittingStaff: "Jendy Perez (EMP-ADM-101)",
    reason: "Motorcycle accident blunt chest trauma surveillance",
    triageTier: "observation",
    status: "Observation",
  },
];

export const INITIAL_VISITOR_LOGS: VisitorLog[] = [
  {
    id: "VIS-2026-01",
    patientId: "P-2024-002",
    patientName: "Carlos Dela Cruz",
    wardBed: "Surgical Ward, Bed 204-A",
    visitorName: "Elena Dela Cruz",
    relationship: "Spouse",
    contactNumber: "0921-777-6543",
    idPresented: "Driver's License (N02-09-1182)",
    badgeNumber: "BADGE-SURG-04",
    timeIn: "2026-09-14 09:30",
    temperatureCelsius: "36.4°C",
    purpose: "Post-op family support and medication verification",
    status: "Currently Visiting",
    loggedByStaff: "Jendy Perez (Admissions)",
  },
  {
    id: "VIS-2026-02",
    patientId: "P-2024-003",
    patientName: "Luzviminda Garcia",
    wardBed: "Medical Ward, Bed 312-B",
    visitorName: "Mark Garcia",
    relationship: "Son",
    contactNumber: "0919-222-8844",
    idPresented: "UMID ID (0011-8492019-3)",
    badgeNumber: "BADGE-MED-12",
    timeIn: "2026-09-14 10:15",
    temperatureCelsius: "36.5°C",
    purpose: "Delivering prescribed dietary supplies and companion care",
    status: "Currently Visiting",
    loggedByStaff: "Jendy Perez (Admissions)",
  },
  {
    id: "VIS-2026-03",
    patientId: "P-2024-004",
    patientName: "Eduardo Mendoza",
    wardBed: "Emergency Obs, Bed ER-03",
    visitorName: "Carmela Mendoza",
    relationship: "Mother",
    contactNumber: "0932-555-6677",
    idPresented: "Voter's ID",
    badgeNumber: "BADGE-ER-02",
    timeIn: "2026-09-14 07:15",
    timeOut: "2026-09-14 11:30",
    temperatureCelsius: "36.6°C",
    purpose: "Intake companion during diagnostic radiograph",
    status: "Departed",
    loggedByStaff: "Jendy Perez (Admissions)",
  },
];

export const INITIAL_SHIFT_ENDORSEMENTS: ShiftEndorsement[] = [
  {
    id: "END-2026-0914-01",
    timestamp: "2026-09-14 07:00",
    shiftPeriod: "Night Shift (23:00–07:00) to Morning Shift (07:00–15:00)",
    ward: "Surgical & Medical Inpatient Wards",
    outgoingNurse: "Maria Lourdes Santos, RN",
    outgoingNurseLicense: "PRC Lic. #0087410",
    incomingNurse: "Angel Mae, RN",
    incomingNurseLicense: "PRC Lic. #0093820",
    patientCensus: 3,
    situation: "Ward census at 3 inpatient beds (1 surgical post-op, 1 cardiac observation, 1 trauma observation).",
    background: "Carlos Dela Cruz on Bed 204-A had mild temperature spike to 38.2°C at 04:00; responded well to antipyretic. Luzviminda Garcia on Bed 312-B received Furosemide 40mg IV at 06:00.",
    assessment: "Bed 204-A wound dressing dry and intact. Bed 312-B dyspnea improving; urine output 650mL for the shift. Bed ER-03 Eduardo Mendoza chest pain VAS 3/10, no crepitus.",
    recommendation: "Continue strict fluid balance on Bed 312-B. Follow up repeat surgical CBC for Bed 204-A at 10:00. Clear Eduardo Mendoza with Dr. Reyes during morning rounds.",
    urgentTasks: [
      "Follow up repeat CBC for Carlos Dela Cruz (Bed 204-A)",
      "Strict urine output chart for Luzviminda Garcia (Bed 312-B)",
      "Re-evaluate chest radiograph report for Eduardo Mendoza (Bed ER-03)",
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "AUD-992",
    timestamp: "2026-09-14 09:30:15",
    userName: "Jendy Perez",
    userRole: "staff",
    userLicense: "EMP-ADM-101",
    action: "Visitor Registered: Elena Dela Cruz for Carlos Dela Cruz (Bed 204-A)",
    targetPatient: "Carlos Dela Cruz",
    patientId: "P-2024-002",
    department: "Admissions Desk",
    ipAddress: "192.168.10.12",
    status: "Authorized",
  },
  {
    id: "AUD-991",
    timestamp: "2026-09-14 08:15:20",
    userName: "Dr. Jose Reyes, MD",
    userRole: "doctor",
    userLicense: "PRC Lic. #0084721",
    action: "Clinical Encounter Review & Medication Order Updated",
    targetPatient: "Carlos Dela Cruz",
    patientId: "P-2024-002",
    department: "Internal Medicine & Surgery",
    ipAddress: "192.168.10.45",
    status: "Authorized",
  },
  {
    id: "AUD-990",
    timestamp: "2026-09-14 07:15:33",
    userName: "Angel Mae, RN",
    userRole: "nurse",
    userLicense: "PRC Lic. #0093820",
    action: "Nursing Shift Handoff Endorsement Logged (SBAR Morning Shift)",
    targetPatient: "Ward Inpatients",
    patientId: "WARD-SURG-MED",
    department: "Nursing Station",
    ipAddress: "192.168.10.82",
    status: "Authorized",
  },
  {
    id: "AUD-989",
    timestamp: "2026-09-13 14:05:44",
    userName: "Atty. Roberto Ramos",
    userRole: "admin",
    userLicense: "IBP Roll #54219",
    action: "Admin System Security & DPA 2012 Compliance Audit Verification",
    targetPatient: "System Wide",
    patientId: "ALL-RECORDS",
    department: "Data Privacy & Compliance",
    ipAddress: "192.168.10.5",
    status: "Authorized",
  },
];

